name: miscelaneos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.1
  sensors_plus: ^6.1.2
  flutter_compass: '^0.8.1'
  dio: ^5.9.0
  share_plus: ^11.1.0
  local_auth: ^2.3.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  quick_actions: ^1.1.0
  workmanager: ^0.9.0+2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
